.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/user-story.md

Added the issue templates from [mentorship-android](https://github.com/anitab-org/mentorship-android), with a few edits to the markdown design.
Fixes #6 

docs: Add issue templates

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

Created a pull request template in .github folder.
Fixes [#7](https://github.com/anitab-org/anitab-org.github.io/issues/7)

Created pull request template

---

.travis.yml
package.json
src/App.test.js
yarn.lock

Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.
Fixes #11
- Code

feat: Travis integration

---

CONTRIBUTING.md

Created a Contribution Guidelines markdown file.
Fixes #12 
- This change requires a documentation update (software upgrade on readme file)
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

docs: Create a Contribution Guidelines markdown file

---

README.md

Readme.md file is updated with relevant description.
Fixes # [14](https://github.com/anitab-org/anitab-org.github.io/issues/14#issue-602851768)

docs: Updated ReadMe's Description.

---

README.md

Explained development setup and run instructions.
Fixes #27 
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

docs: Explain development setup and run instructions

---

public/index.html

change web title from react app to AnitaB org open source
Fixes #25
- Code

change web title from react app to AnitaB org open source

---

README.md

Updated README.md to include the link to the project stream on Zulip.
Fixes #28 28 -Add reference to new stream on Zulip on README ]
- This change requires a documentation update (software upgrade on readme file)
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

Updated Contact Section in README.md to include link to this project's stream on Zulip.

---

src/aboutUs.json

Add 4 short descriptions to About Us page
Fixes #46 
**Add `aboutUs.json` file for About Us page**
N/A
**Resources**
* http://wiki.systers.org/open-source/doku.php
* https://anitab.org/systers/systers-initiatives/
* https://codein.withgoogle.com/organizations/systers-an-anitaborg-community/
* http://systers-opensource.blogspot.com/
* https://summerofcode.withgoogle.com/organizations/4752039663370240/
* http://systers.io/

Add 4 short descriptions to About Us page

---

src/Components/Content/index.js
src/Components/Footer/Form.js
src/Components/Projects/index.js

In Components/Content/index.js, renderContent() was declared 2 times.
Fixes #107 
- Code
Tested it locally.

Bugs: Fixed renderContent() content declaration

---

.travis.yml
package.json

This will trigger deployment to GitHub pages https://anitab-org.github.io/test-anitab-org/ whenever any merge to develop branch has been done. 
While it's great to use Heroku we need to make sure our changes works on GitHub pages as long as this is a production environment.
Fixes #106
- Code
- Quality Assurance
- This change requires a documentation update (software upgrade on readme file)
https://anitab-org.github.io/test-anitab-org/

Deploy to testing GitHub pages on develop change.

---

README.md

Description
Created badges in README.md
Fixes #112 
Type of Change:
Delete irrelevant options.
Documentation
Code/Quality Assurance Only
This change requires a documentation update (software upgrade on readme file)
Delete irrelevant options.

content: Added badges in README

---

README.md

Updated the Zulip stream link from design to anitab-oorg.github.io on README.md
Fixes #126 

docs: update zulip stream link

---

public/index.html

Added the SEO (Search Engine Optimization) for the web pages.
Fixes #187 
- Code: Added Meta tags
- Quality Assurance: :100: 
- User Interface: Not changed
- Documentation: Doesn't need any change
- [ :+1: ] My PR follows the style guidelines of this project
- [ :+1: ] I have performed a self-review of my own code or materials
- [ :+1: ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ :+1: ] I have made corresponding changes to the documentation
- [ :+1: ] Any dependent changes have been merged
- [ :+1: ] My changes generate no new warnings
- [ :+1: ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ :+1: ] I have added tests that …

Added SEOs for the web pages

---

package.json
src/test/AboutUs.test.js
src/test/Contribute.test.js
src/test/Home.test.js
src/test/OurEvents.test.js
src/test/Projects.test.js
src/test/__snapshots__/AboutUs.test.js.snap
src/test/__snapshots__/Contribute.test.js.snap
src/test/__snapshots__/Home.test.js.snap
src/test/__snapshots__/OurEvents.test.js.snap
src/test/__snapshots__/Projects.test.js.snap
yarn.lock

Snapshot test for each component using jest .
Fixes #23 
- Code
- Quality Assurance
- User Interface
its does cannot be checked with hosted website on github.

Feat: added snapshot test for components

---

src/content/about_us.json
src/content/home.js
src/content/home.json
src/content/our_events.js
src/content/our_events.json
src/content/projects_content.js
src/test/__snapshots__/AboutUs.test.js.snap
src/test/__snapshots__/Home.test.js.snap
src/test/__snapshots__/OurEvents.test.js.snap
src/test/__snapshots__/Projects.test.js.snap

This PR fixes some grammatical errors from different pages.
Fixes #203 
- Coding
Screenshots of the bug fixes
Home Page
Projects
About Us
Events
All the test cases ran successfully.
Jest Output

Grammatical error fixes

---

src/content/about_us.json

added medium publication link to about section
Fixes #201 
- Code
- User Interface
testing screenshot:

feat: added medium publication link in about section

---

src/content/our_events.js

Removed TITLE2 and duplicate image as discussed with the mentor
Fixes #199 

fix: TITLE 2 instead of proper title in events tab

---

src/content/projects_content.js
yarn.lock

Added react.js tag for Open Source Programs Web project in projects
Fixes #211 
- Code

fix: Add react.js tag for Open Source Programs Web Project

---

src/Components/Contribute/index.js
src/Components/Contributors/index.js
src/Components/Events/index.js
src/Components/Home/contribution/ContributionCard.js
src/Components/Home/contribution/ContributionSection.js
src/Components/Home/index.js
src/Components/ImageTextSection/index.js
src/Components/OurEvents/index.js
src/Components/Programs/Timeline.js
src/Components/Projects/ProjectCard/index.js

map method in some components didn't had the key props.
Fixes #215 
Added key props in components :
1. ContributionSection
2. ContributionCard
3. Home
4. Projects
5. Events
6. Contribute

updated key props

---

src/Components/Programs/Timeline.js
src/Components/Programs/styles.js

Placed footer at bottom and timeline at center in programs tab
Fixes #224 
- Code

Fix : Place Footer at bottom and Timeline at center in programs tab

---

src/Components/Programs/Timeline.js
src/Components/Programs/styles.js

Made the Icon and Text clickable as a whole and changed a bit of styling to make them look clickable.
Fixes #251 
- Code
- User Interface

Fix #251 Bug : Programs Page buttons not designed properly

---

src/Components/Footer/Social.js
yarn.lock

The social links in the footer open in a new tab on clicking them.
Fixes #260 
- Code
- Bug fix #260 
By running the site on localhost, I have verified that the social handles links in the footer will open in a new tab.

Fix #260 social links in footer will open in new tab

---

README.md

Update Prerequisites from React-Native to ReactJS
Fixes # [255 ](https://github.com/anitab-org/anitab-org.github.io/issues/255)
- This change requires a documentation update (software upgrade on readme file)
If you are working on a design then add a gif to show the responsiveness of your design.
Please follow [testing guidelines](https://github.com/anitab-org/anitab-org.github.io/wiki/Prepare-testing-GitHub-Pages-for-your-PR) and share the link of deployed site here.

Updated Prerequisites from React-Native to ReactJS

---

src/content/projects_content.js

Add STEM-Diverse-TV-CMS in the projects list
Fixes #228 
- Code
- User Interface

Fix: Add STEM-Diverse-TV-CMS in the projects list

---

src/Components/Footer/Social.js

Just adding the "import Linking" at the top of ./src/Components/Footer/Social.js 😊 
Fixes #280
- Code
If you are working on a design then add a gif to show the responsiveness of your design.
Please follow [testing guidelines](https://github.com/anitab-org/anitab-org.github.io/wiki/Prepare-testing-GitHub-Pages-for-your-PR) and share the link of deployed site here.

Add Linking to import from 'react-native'

---

src/content/home.js

Provided the line breaks wherever required for better readability. 
Fixes #192 

fix: Documentation needs text formatting for better readability

---

src/content/projects_content.js
src/test/__snapshots__/Projects.test.js.snap

Added an archived section to the projects page.
Fixes #301
- Code: In `anitab-org.github.io\src\content\projects_content.js` added a new objects with title `Archives` to the `sections` list
- User Interface: new section added to the projects page

feat: archive section added to projects page

---

src/content/projects_content.js
src/test/__snapshots__/Projects.test.js.snap

Fixes #355 
Code
Bug fix (non-breaking change which fixes an issue)
My PR follows the style guidelines of this project
I have performed a self-review of my own code or materials
My changes generate no new warnings

fixing typo in the archive page under Projects

---

.github/config.yml

Fixes #323 
- Code
- Quality Assurance

feat:fixed welcome bot
